spring:
  datasource:
    url: jdbc:mysql://localhost:3307/collector?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: "collector123"

  data:
    redis:
      host: localhost
      port: 6379
      password: "collector_redis"

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

collector:
  admin:
    username: admin
    password-hash: "$2b$10$juchQKeDjBxIMx8AsidnBuOfv7eHU0sXKac1Jl191mXLf0UbyO5Vy"
  jwt:
    secret: "dev-secret-key-must-be-at-least-64-bytes-long-for-hs512-algorithm-so-here-it-is-padded"

logging:
  level:
    com.collector: DEBUG
    org.springframework.web: INFO
